### ISSUE TITLE
Read UID with ACR122U

### ISSUE THREAD

**Issue by js-landoo** [AppliedEllipsis/pyACR1252U#1]
Hi.
First of all, thanks for this interesting work. It looks like could solve my actual need with some updates.

I'm using an ACR122U device and I'd like to read UID from ntags and show it on cursor position, like keyboard emulator.
I've tried your binaries and also to generate my own ones (it was smooth, thanks to your precise documentation).
None of them gives me desired data. Can you tell how to change code to obtain UID?

If it helps, card reader is recognized, if I try to record a code it says it's done, but if I try to read code, nothing is shown, not in NFC.exe windows, not in cursor position (notepad).

Thanks a lot.

**Comment by rcourtney** [comment]
The unmodified NFC program works with NTAG213 and NTAG216 from NXP.
Does the reader beep twice when you start the program?

Can you take a screenshot of the log area of the program? (example below)



Page 12 from
https://www.nxp.com/documents/data_sheet/NTAG213_215_216.pdf
describes how to form the UID.

Richard

**Comment by rcourtney** [comment]
It also looks like there is some differences in the APDU commands 
between the ACR122U and ACR1252.

For ACR122U:
http://www.acs.com.hk/download-manual/419/API-ACR122U-2.03.pdf

For ACR1252U:
http://www.acs.com.hk/download-manual/6402/API-ACR1252U-1.09.pdf

refer to line 324 of the program source    # read binary block
INS 0xB1 instead of INS 0xB0

I don't have time tonight to review both readers but you have a start.

**Comment by rcourtney** [comment]
Josean,
Disregard the INS values mentioned.  I am tired from a long day.
0xB0 is fine.

Richard

**Comment by js-landoo** [comment]
Hi Richard.

Thank you very much for your help.
I'm looking for the easiest way to connect any NFC reader, doesn't matter wich model, and ACS company has answer me telling they have another model with HID interface. Emulates keyboard so is just pluging and works. Reads UID and shows it in cursor position, in any application.
So I've decided to return ACS122U reader and purchase ACR1281U-C2

Thank you again for your fast answer and best regards.
